### ISSUE TITLE
Compile pr2plan

### ISSUE THREAD

**Issue by mhd0528** [karthikv792/LLMs-Planning#1]
Hi, 

May I ask what's the Linux system you are using? I have been trying to compile the pr2plan package on my Ubuntu 18.04 & 20.4 systems, but I keep getting errors about lib files missing. 

Thanks.

**Comment by karthikv792** [comment]
It was compiled on an older machine (16.04). You can find the compiled executable here which can be used in the newer linux machines too.
https://github.com/karthikv792/RADAR-X/blob/master/planner/PR2/pr2plan

**Comment by mhd0528** [comment]
It works now. Thanks so much!
