### ISSUE TITLE
how to make VAL work?

### ISSUE THREAD

**Issue by wenjunli-0** [karthikv792/LLMs-Planning#10]
I am trying to evaluate the responses. 

I downloaded the repo and set os.environ['VAL'] = '/home/wenjun/2024PlanBench/planner_tools/VAL. However, when I tried to evaluate the responses, I got the error "/bin/sh: 1: /home/wenjun/2024PlanBench/planner_tools/VAL/validate: Permission denied".

Should I install the validate package or something? 

Please help me and thank you in advance.

**Comment by karthikv792** [comment]
There is no need to install the validate package. It is a binary that you should be able to execute.
Maybe try to change the access permissions of validate using chmod and that might help you out.

**Comment by Zxy-MLlab** [comment]
Can your VAL be evaluated correctly? Download I'm asking for VAL, then set the environment variable: for its os.environ['VAL'] =/home/zhouxueyang/agent/plan/planbench/LLMs-Planning-main/plan-bench/VAL-master. 

But when I evaluated the response, '/home/zhouxueyang/agent/plan/planbench/LLMs-Planning-main/plan-bench/VAL-master/validate ./instances/blocksworld/generated_domain.pddl ./instances/blocksworld/generated_basic/instance-10.pddl llm_plan', 

it always returns "", is there something wrong with my deployment? @karthikv792
