### ISSUE TITLE
No sas_plan file and no groundtruth

### ISSUE THREAD

**Issue by wenjunli-0** [karthikv792/LLMs-Planning#11]
Appreciate the repo and contribution. I met the following issue when trying to generate the prompts. 

1. there is no sas_plan file. There were two issues on this bug and I checked them carefully, but I didn't find a solution from there. 

2. If I manually create a sas_plan file and copy the lines from gpt_sas_file and paste them in sas_plab. All the ground truths in the prompts file become the same. Like this "ground_truth_plan": "(unstack yellow orange)\n(put-down yellow)\n(pick-up orange)\n(stack orange red)\n".

I guess the sas_plan is for generating ground truth in pddl. Please help me and I really appreciate your effort. Thank you.

**Comment by karthikv792** [comment]
So you can change this line in compute_plan function in prompt_generation.py from
`cmd = f"{fast_downward_path}/fast-downward.py {domain} {instance} --search \"astar(lmcut())\" > /dev/null 2>&1"`
to
`cmd = f"{fast_downward_path}/fast-downward.py {domain} {instance} --search \"astar(lmcut())\""`
This would essentially print the entire output of the Fast Downward planner. That's a potential source of the issue.

**Comment by wenjunli-0** [comment]
> So you can change this line in compute_plan function in prompt_generation.py from `cmd = f"{fast_downward_path}/fast-downward.py {domain} {instance} --search \"astar(lmcut())\" > /dev/null 2>&1"` to `cmd = f"{fast_downward_path}/fast-downward.py {domain} {instance} --search \"astar(lmcut())\""` This would essentially print the entire output of the Fast Downward planner. That's a potential source of the issue.

many thanks @karthikv792. This works.
