### ISSUE TITLE
Bugs with problem_generator.py

### ISSUE THREAD

**Issue by wenjunli-0** [karthikv792/LLMs-Planning#12]
I think there are a few bugs in the problem_generator.py. 

For example, 
self.data is None (https://github.com/karthikv792/LLMs-Planning/blob/de1b3ddb964849b25144135f360221e20e0c05df/llm_planning_analysis/problem_generators.py#L14), 
the config file should end up with yaml (https://github.com/karthikv792/LLMs-Planning/blob/de1b3ddb964849b25144135f360221e20e0c05df/llm_planning_analysis/problem_generators.py#L469), 
and etc.

Could you please help to fix the bugs in problem_generator.py?

**Comment by karthikv792** [comment]
The self.data=None should be fine but thanks for pointing out the config file issue. 
Yes it should be a .yaml file.
`config_file = f'configs/{config_file}.yaml' `
