### ISSUE TITLE
gpt-actions.py is not executing fully

### ISSUE THREAD

**Issue by anirbankarak** [karthikv792/LLMs-Planning#2]
While running **gpt-actions.py**  I found out  if block `if cnt > 0`  from line 109 to 133 is not executing because of line 80 `cnt -= 1` .
Is it intentional or some logic behind it.

**Comment by karthikv792** [comment]
The `cnt-=1` is essentially to count the number of correct outputs. The 109-133 if block only executes if there is atleast one correct output from the LLM
