### ISSUE TITLE
No such file or directory: 'sas_plan'

### ISSUE THREAD

**Issue by henkebent** [karthikv792/LLMs-Planning#5]
I tried to run the provided example in /gpt_plan_test

`python3 ReasoningTasks.py --task t1 --engine davinci --verbose True`

in Google Colab, but am receiving the error:

```
File "/content/gpt-plan-benchmark/gpt_plan_test/utils/__init__.py", line 294, in get_plan_as_text
    with open(plan_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sas_plan
```

I can of course add a file "sas_plan" myself manually, but I have no idea what is supposed to be in it since the README does not mention it. Is it supposed to be auto-generated?

**Comment by henkebent** [comment]
Nevermind, I had made some mistakes of my own.

**Comment by jivatneet** [comment]
Hi @henkebent , would you mind sharing the mistakes as I am facing the same error, thanks!

**Comment by henkebent** [comment]
@jivatneet Hi, I don't remember exactly the mistakes I made but I uploaded a colab notebook here: https://github.com/henkebent/gpt_plan_test_colab/blob/main/Copy_of_gpt_plan_test.ipynb

that seems to work.

**Comment by jivatneet** [comment]
Thanks a lot, this worked!

**Comment by wenjunli-0** [comment]
> 

hi @jivatneet, do you know which step/command solves the bug? I met the same issue. Thank you.
