### ISSUE TITLE
No such file or directory: 'sas_plan'

### ISSUE THREAD

**Issue by HaochenZhang717** [karthikv792/LLMs-Planning#6]
I run the code by "python3 llm_plan_pipeline.py --task 't1' --config 'blocksworld' --engine ada", but get error as 
Traceback (most recent call last):
  File "/home/hchen/LLMs_planning/plan-bench/llm_plan_pipeline.py", line 66, in <module>
    prompt_generator.task_1_plan_generation(specified_instances, random_example)
  File "/home/hchen/LLMs_planning/plan-bench/prompt_generation.py", line 152, in task_1_plan_generation
    gt_plan_text = get_plan_as_text(self.data)
  File "/home/hchen/LLMs_planning/plan-bench/utils/pddl_to_text.py", line 131, in get_plan_as_text
    with open(plan_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'sas_plan'

does anyone have the same bug? and how do you fix this?

**Comment by thongonary** [comment]
I ran into the same issue. Creating a blank `sas_plan` file solved it for me. 

EDIT: Nevermind it doesn't work. The code run but the instruction generated was blank.

**Comment by karthikv792** [comment]
If this still persists, kindly refer to this [issue](https://github.com/karthikv792/LLMs-Planning/issues/5).
Thank you.

**Comment by wenjunli-0** [comment]
> I run the code by "python3 llm_plan_pipeline.py --task 't1' --config 'blocksworld' --engine ada", but get error as Traceback (most recent call last): File "/home/hchen/LLMs_planning/plan-bench/llm_plan_pipeline.py", line 66, in prompt_generator.task_1_plan_generation(specified_instances, random_example) File "/home/hchen/LLMs_planning/plan-bench/prompt_generation.py", line 152, in task_1_plan_generation gt_plan_text = get_plan_as_text(self.data) File "/home/hchen/LLMs_planning/plan-bench/utils/pddl_to_text.py", line 131, in get_plan_as_text with open(plan_file) as f: FileNotFoundError: [Errno 2] No such file or directory: 'sas_plan'
> 
> does anyone have the same bug? and how do you fix this?

hi @HaochenZhang717, have you fixed this bug? I met the same issue.

**Comment by wenjunli-0** [comment]
> I ran into the same issue. Creating a blank `sas_plan` file solved it for me.
> 
> EDIT: Nevermind it doesn't work. The code run but the instruction generated was blank.

hi @thongonary, have you fixed this issue?
