### ISSUE TITLE
plan-bench Requirements no links

### ISSUE THREAD

**Issue by LWMin** [karthikv792/LLMs-Planning#8]
The Requirements in the README of plan-bench about Fast Downward, VAL and PR2Plan related links jump to empty pages and cannot be downloaded.
In addition, the CONFIG.Yaml file does not exist in the /plan-bench/config/ file

**Comment by wenjunli-0** [comment]
hi @LWMin, have you downloaded the files? I am also having this issue

**Comment by karthikv792** [comment]
I have updated the links to download the required tools. I have also provided some tools in the repo itself. Hope that is useful. Thank you.
